import { 
    IGameInfoAction, 
    UPDATE_HOSTURL, 
    UPDATE_PROGRESS, 
    UPDATE_VIEWERS,
    UPDATE_CONNECTION_STATUS,
} from './IGameInfoAction';

export {
    IGameInfoAction,
    UPDATE_HOSTURL, UPDATE_PROGRESS, UPDATE_VIEWERS, UPDATE_CONNECTION_STATUS
}